title:              Zeeshan Munir
email:              zeeshan.munir307@gmail.com
description:        Mobile App Developer | iOS | React Native
author:             
baseurl:            ""
url:                "https://zeeshanmunir.github.io"

# Social Profiles
github_username:    zeeshanmunir
linkedin_username:  zeeshan-munir-24ba08137

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
